name: Deploy Node.js App to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./WestEU

      - name: Deploy to WestEU1 Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: WestEU1
          publish-profile: ${{ secrets.secret123 }}
          package: ./eastusapp
